#' Predicting playoff series results
#'
#' @param teamH The team with home-court advantage (HCA) for the series.
#' @param teamA The team without home-court advantage.
#' @param t1pH Probability of the team with HCA winning at home.
#' @param t1pA Probability of the team with HCA winning, when they play on the road.
#'
#' @return A numeric vector with probabilities of each possible series outcome.
#'
#' @keywords internal
#'
#' @author astroud
seriesOutcomes = function(teamH, teamA, t1pH, t1pA) {
  h4 = t1pH^2*t1pA^2
  h5 = (2*t1pH^3*t1pA*(1-t1pA)) + (2* t1pH^2*t1pA^2*(1-t1pH))
  h6 = (6*t1pH^2*t1pA^2*(1-t1pH)*(1-t1pA)) + (3*t1pH*t1pA^3*(1-t1pH)^2) + (t1pH^3*t1pA*(1-t1pA)^2)
  h7 = (t1pH^4*(1-t1pA)^3) + (9*t1pH^3*t1pA*(1-t1pH)*(1-t1pA)^2) + (9*t1pH^2*t1pA^2*(1-t1pH)^2*(1-t1pA)) + (t1pA^3*t1pH*(1-t1pH)^3)
  a7 = ((1-t1pH)^4*t1pA^3) + (9*(1-t1pH)^3*(1-t1pA)*t1pH*t1pA^2) + (9*(1-t1pH)^2*(1-t1pA)^2*t1pH^2*t1pA) + ((1-t1pA)^3*(1-t1pH)*t1pH^3)
  a6 = (6*(1-t1pH)^2*(1-t1pA)^2*t1pH*t1pA) + (3*(1-t1pH)*(1-t1pA)^3*t1pH^2) + ((1-t1pH)^3*(1-t1pA)*t1pA^2)
  a5 = (2*(1-t1pH)^3*(1-t1pA)*t1pA) + (2*(1-t1pH)^2*(1-t1pA)^2*t1pH)
  a4 = (1-t1pH)^2*(1-t1pA)^2

  results = c(h4, h5, h6, h7, a7, a6, a5, a4)
  names(results) = c(paste(teamH, "in", 4:7), paste(teamA, "in", 7:4))
  results
}

#' Bar plot predicting playoff series outcomes
#'
#' @details This barplot is currently a fairly poor visualization - one of our
#' primary TODOs is to clean up and prettify the visualization it gives. We plan
#' on learning ggplot to implement this.
#'
#' @param home The team with home-court advantage in the series.
#' @param away The team without home-court advantage.
#' @param outcomes A vector with all possible outcomes of a 7-game
#' playoff series (e.g. Home wins in 6), each with its associated probability.
#' @return A bar plot showing the probability of each playoff series outcome.
#'
#' @importFrom graphics barplot
#'
#' @keywords internal
#'
#' @author kitliu5
plotSeriesOutcomes = function(home, away, outcomes) {
  graphics::barplot(outcomes,
                    main=paste(home, "(H)", "vs.", away, "(A)", "Playoff Series Prediction", sep = " "),
                    horiz=TRUE,
                    names.arg=names(outcomes))
}


#' Bar plot predicting playoff series
#'
#' @details Note that while both the Elo model and Bradley-Terry model
#' use three-letter abbreviations to refer to teams, these abbreviations
#' differ because the models are built using datasets from different sources
#' (FiveThirtyEight versus stats.nba.com). Thus, be careful when specifying
#' team names. We hope to add a function in the future that will allow for
#' easier conversion between team names and abbreviations.
#'
#' @param prob A probability matrix with each entry representing the
#' probability of the team in that row defeating the tean in that
#' column. It can be generated by \code{\link{buildWinProbMatrixBT}} or
#' \code{\link{buildWinProbMatrixElo}}.
#' @param home The team with home-court advantage in the series.
#' @param away The team without home-court advantage.
#' @param plot A logical value indicating whether the user would
#' like to generate a barplot of series outcomes.
#' @return A numeric vector giving the probability of each playoff series outcome.
#'
#' @export
#'
#' @examples
#' playoffSeries(seasonWinProb2017, home = "BOS", away = "SAS")
#' @author kitliu5 and astroud
playoffSeries = function(prob, home, away, plot = FALSE){
  if (! home %in% prob$Team){
    stop("Home team is unavailable")
  }
  if (! away %in% prob$Team){
    stop("Away team is unavailable")
  }

  homeWinProb = prob[which(prob$Team == home), which(colnames(prob) == away)]
  awayWinProb = 1 - prob[which(prob$Team == away), which(colnames(prob) == home)]

  resultsDistribution = seriesOutcomes(home, away, homeWinProb, awayWinProb)

  ####################
  # begin astroud code
  if(plot) {
    plotSeriesOutcomes(home, away, resultsDistribution)
  }

  results = c(sum(resultsDistribution[1:4]), sum(resultsDistribution[5:8]), resultsDistribution)
  names(results) = c(home, away, names(resultsDistribution))

  results
  # end astroud code, all other code by kitliu5
  #############################################
}
